### ISSUE TITLE
diffs of witcher script files don't work (states binary file)

### ISSUE THREAD

**Issue by madman-asunder** [adam-sunderman/modW3ReduxRGC#2]
I'm doing some research and I think it has to do with .gitattributes (which I don't have any right now) but if anyone knows how to make sure diffs show properly for edits to witcher script / xml / etc. let me know here. I will leave this issue open till I figure it out.

**Comment by adam-sunderman** [comment]
After communication with wsghost81, I have updated .gitattributes with *.ws *.csv and *.xml

**Comment by madman-asunder** [comment]
what a royal pain. fixed via convertToUTF8.sh script. See https://github.com/adam-sunderman/modW3ReduxAPI for example. Feel free to reopen this issue to ask questions if you are facing this issue on your own work.
